language: ruby
script: 'bundle exec rake'
sudo: false
rvm:
  - 2.2.5
services:
  - mongodb

notifications:
  email:
    recipients:
      - joost@spacebabies.nl
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never

matrix:
  allow_failures:
    - rvm: ruby-head
  matrix:
    include:
      - rvm: 2.3.3
        env: MONGOID_VERSION=5
      - rvm: 2.3.3
        env: MONGOID_VERSION=6
      - rvm: 2.5.1
        env: MONGOID_VERSION=7
